### ISSUE TITLE
Uncaught InvalidMultipartContentException when the boundary is missing

### ISSUE THREAD

**Issue by leogr** [zfcampus/zf-content-negotiation#60]
If the `MultipartContentParser` is unable to detect MIME boundary an `InvalidMultipartContentException` is thrown (see [here](https://github.com/zfcampus/zf-content-negotiation/blob/1.1.1/src/MultipartContentParser.php#L32)). 

When that happens within the `ContentTypeListener` (see [here](https://github.com/zfcampus/zf-content-negotiation/blob/1.1.1/src/ContentTypeListener.php#L82)) then the exception is not caught so a fatal error occurs: 

```
<br />
<b>Fatal error</b>:  Uncaught exception 'ZF\ContentNegotiation\Exception\InvalidMultipartContentException' in /var/www/vendor/zfcampus/zf-content-negotiation/src/MultipartContentParser.php:35
Stack trace:
#0 /var/www/vendor/zfcampus/zf-content-negotiation/src/ContentTypeListener.php(82): ZF\ContentNegotiation\MultipartContentParser-&gt;__construct(Object(Zend\Http\Header\ContentType), Object(ZF\ContentNegotiation\Request))
#1 [internal function]: ZF\ContentNegotiation\ContentTypeListener-&gt;__invoke(Object(Zend\Mvc\MvcEvent))
#2 /var/www/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Object(ZF\ContentNegotiation\ContentTypeListener), Object(Zend\Mvc\MvcEvent))
#3 /var/www/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager-&gt;triggerListeners('route', Object(Zend\Mvc\MvcEvent), Object(Closure))
#4 /var/www/vendor/zendframework/zend-mvc/src/Application.php(297): Zend\EventManager\EventManager-&gt;trigger('route', Object(Zend\Mvc in 
<b>/var/www/vendor/zfcampus/zf-content-negotiation/src/MultipartContentParser.php</b> on line 
<b>35</b>
<br />
```

I would suggest that you move the `MultipartContentParser` within the `try...catch` block, so:
```
try {
    $parser = new MultipartContentParser($contentType, $request);
    $bodyParams = $parser->parse();
} catch (Exception\ExceptionInterface $e) {
    $bodyParams = new ApiProblemResponse(new ApiProblem(
        400,
        $e
    ));
    break;
}
```
In this way a 400 Bad Request will be returned, instead of getting a fatal error.

If you agree with my solution I can make a PR.

**Comment by theboolean** [comment]
+1, any news about this issue?

**Comment by leogr** [comment]
I made a PR #63
